version: '3.8'

services:
  auth_db:
    image: mongo:6.0
    container_name: auth-mongo-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: authdb
      MONGO_INITDB_ROOT_USERNAME: auth_user
      MONGO_INITDB_ROOT_PASSWORD: authcompnypoint1
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  auth_service:
    build:
      context: .
    container_name: auth-service-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://auth_user:authcompnypoint1@auth-mongo-db:27017/authdb?authSource=admin"
      JWT_SECRET: "secretkey123"
    depends_on:
      - auth_db
    command: ["npm", "start"]

volumes:
  auth_data:

